alias zshrc="vim ~/.zshrc"
alias py="python3"
alias python="python3"
alias reload="source ~/.zshrc"
alias proxy="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"
alias profile="code ~/.zshrc"
alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy"
alias download="curl -O"
alias now="date +'%Y-%m-%d %H:%M:%S'"
alias nowtime="date +'%H:%M:%S'"
alias nowdate="date +'%Y-%m-%d'"
alias nowtimestamp="date +%s"
alias nowtimestampms="date +%s%3N"
alias nowtimestampus="date +%s%6N"
alias nowtimestampns="date +%s%9N"
alias cp-now="now | pbcopy"